@startuml database

!theme sketchy-outline

Artist "*" -right- "*" Genre

Album "*" - "*" Track
(Album, Track) .. AlbumTrack
Album "*" --- "*" Artist

Track "*" - "*" Artist
Track "1" - "1" TrackFeatures

Genre : name

Artist : uri
Artist : name
Artist : popularity

Album : uri
Album : name
Album : album_type
Album : release_date
Album : total_tracks

Track : uri
Track : name
Track : duration_ms
Track : lyrics
Track : explicit

TrackFeatures : acousticness
TrackFeatures : danceability 
TrackFeatures : energy
TrackFeatures : instrumentalness
TrackFeatures : liveness
TrackFeatures : loudness
TrackFeatures : mode
TrackFeatures : speechiness
TrackFeatures : tempo
TrackFeatures : time_signature
TrackFeatures : valence

AlbumTrack : track_number

@enduml
