@startuml database

!theme sketchy-outline

Album "*" -- "*" Track
(Album, Track) .. TrackPosition
Album "*" -- "*" Genre
Album "*" -- "*" Artist
Artist "*" -- "*" Genre
Track "*" -- "*" Genre
Track "*" -- "*" Artist
Track "1" *-- "1" Lyrics

Album : name
Artist : name
Genre : name
Lyrics : lyrics_text
Track : name
Track : duration_ms
TrackPosition : position_num

@enduml