@startuml database

!theme sketchy-outline

Artist "*" - "*" Genre

Album "*" -- "*" Track
(Album, Track) .. AlbumTrack
Album "*" - "*" Genre
Album "*" - "*" Artist

Track "*" - "*" Artist

Genre : name

Artist : uri
Artist : name
Artist : popularity

Album : uri
Album : name
Album : album_type
Album : release_date
Album : total_tracks

Track : uri
Track : name
Track : duration_ms
Track : lyrics
Track : popularity
Track : acousticness
Track : danceability 
Track : energy
Track : instrumentalness
Track : liveness
Track : loudness
Track : mode
Track : speechiness
Track : tempo
Track : time_signature
Track : valence

AlbumTrack : track_number

@enduml
